### ISSUE TITLE
Intersection of Feature Sets

### ISSUE THREAD

**Issue by mengjiang1994** [ViDA-NYU/data-polygamy#3]
Hi **@fchirigati** 

It's me again, could you please give me a brief of how to compute the intersection of feature sets, and representing each set of features as a bit vector? Could you please give me a simple example?

Regards,

Meng

**Comment by fchirigati** [comment]
Hi @mengjiang1994 

Sure. Each type of point (positive feature, negative feature, and non-feature) is defined as a byte (bit vector) so that each type of intersection gives a different value when using the OR operator.

For instance, a non-feature is defined as `001`, so a non-feature intersecting a non-feature will always give `(001 OR 001) = 001`; a positive feature is defined as `010`, so positive feature with non-feature will always give `(001 OR 010) = 011`; and so on. So, by looking at the "value of the intersection", we can easily check which type of intersection it is.

The values are defined [here](https://github.com/ViDA-NYU/data-polygamy/blob/master/data-polygamy/src/main/java/edu/nyu/vida/data_polygamy/utils/FrameworkUtils.java#L2391), and the intersections are computed [here](https://github.com/ViDA-NYU/data-polygamy/blob/master/data-polygamy/src/main/java/edu/nyu/vida/data_polygamy/relationship_computation/CorrelationReducer.java#L623).

Let me know if you have any further questions.

Thanks for your interest in Data Polygamy! How you are planning to use the framework?

**Comment by mengjiang1994** [comment]
Hi @fchirigati 

Sorry for reply lately. I'm a student in university and Data Polygamy is the core part of my master thesis.

I'm trying to find some interesting relationships between the weather and the bikeway counting of my city. I actually found some, like the weak negative relationships between the rainfall and the number of cyclists in city-week level.

Again, thank you for your help, it's my pleasure to communicate with you.

@mengjiang1994

**Comment by fchirigati** [comment]
@mengjiang1994 Cool! I would love to take a look at your thesis whenever it is done!

Good luck, and do let me know if you have any other question!
